{
	"selectionId": 86856232,
	"runnerName": "15. Robyn Rocks Heaven",
	"handicap": 0.0,
	"sortPriority": 14,
	"metadata": {
		"SIRE_NAME": "Rock N Roll Heaven",
		"CLOTH_NUMBER_ALPHA": "15",
		"OFFICIAL_RATING": null,
		"COLOURS_DESCRIPTION": "Purple Red Sash Gold Sleeves & Red Armbands (T)",
		"COLOURS_FILENAME": "c20250810trots_ASCOTPARKRACEWAY/2334306.png",
		"FORECASTPRICE_DENOMINATOR": null,
		"DAMSIRE_NAME": "Holmes Hanover",
		"WEIGHT_VALUE": null,
		"SEX_TYPE": "G",
		"DAYS_SINCE_LAST_RUN": "7",
		"WEARING": null,
		"OWNER_NAME": null,
		"DAM_YEAR_BORN": null,
		"SIRE_BRED": "USA",
		"JOCKEY_NAME": "Hayden Douglas",
		"DAM_BRED": "NZ",
		"ADJUSTED_RATING": null,
		"runnerId": "86856232",
		"CLOTH_NUMBER": "15",
		"SIRE_YEAR_BORN": null,
		"TRAINER_NAME": "Ross & Chris Wilson",
		"COLOUR_TYPE": "B",
		"AGE": "3",
		"DAMSIRE_BRED": "USA",
		"JOCKEY_CLAIM": null,
		"FORM": "9",
		"FORECASTPRICE_NUMERATOR": null,
		"BRED": "NZ",
		"DAM_NAME": "Robyn Joan",
		"DAMSIRE_YEAR_BORN": null,
		"STALL_DRAW": "15",
		"WEIGHT_UNITS": null
	},
	"eventType": {
		"id": "7",
		"name": "Horse Racing"
	},
	"event": {
		"id": "34603283",
		"name": "Ascot Park (NZL) 10th Aug",
		"countryCode": "NZ",
		"timezone": "NZ",
		"venue": "Ascot Park",
		"openDate": "2025-08-09T23:50:00.000Z"
	},
	"id": 1
},
{"selectionId":86856231,"runnerName":"14. Mighty Miki","handicap":0.0,"sortPriority":13,"metadata":{"SIRE_NAME":"Always B Miki","CLOTH_NUMBER_ALPHA":"14","OFFICIAL_RATING":null,"COLOURS_DESCRIPTION":"Red Black & Gold Chequered Sash","COLOURS_FILENAME":"c20250810trots_ASCOTPARKRACEWAY/2133184.png","FORECASTPRICE_DENOMINATOR":null,"DAMSIRE_NAME":"Mach Three","WEIGHT_VALUE":null,"SEX_TYPE":"G","DAYS_SINCE_LAST_RUN":"7","WEARING":null,"OWNER_NAME":null,"DAM_YEAR_BORN":null,"SIRE_BRED":"USA","JOCKEY_NAME":"Matthew Williamson","DAM_BRED":"NZ","ADJUSTED_RATING":null,"runnerId":"86856231","CLOTH_NUMBER":"14","SIRE_YEAR_BORN":null,"TRAINER_NAME":"Matthew Williamson","COLOUR_TYPE":"B","AGE":"4","DAMSIRE_BRED":"CAN","JOCKEY_CLAIM":null,"FORM":"25242","FORECASTPRICE_NUMERATOR":null,"BRED":"NZ","DAM_NAME":"Touch Of Rose","DAMSIRE_YEAR_BORN":null,"STALL_DRAW":"14","WEIGHT_UNITS":null}},
